/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankingsystem;

/**
 *
 * @author ASUS
 */
public class Setting extends javax.swing.JFrame {
    int accId;
    boolean frame;
    public static String posit;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Setting.class.getName());

    /**
     * Creates new form Setting
     */
    public Setting() {
    setUndecorated(true);   // IMPORTANT
    initComponents();
}
    public Setting(int id) {
    accId = id;    
    setUndecorated(true);   // IMPORTANT
    initComponents();
}
    public Setting(int id, boolean aiframe, String pos) {
        accId = id;
        frame = aiframe;
        posit = pos;
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        SettingPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cPinBtn = new javax.swing.JButton();
        aboutUsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SettingPanel.setBackground(new java.awt.Color(133, 14, 53));
        SettingPanel.setForeground(new java.awt.Color(133, 14, 53));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Setting");
        jLabel2.setMaximumSize(new java.awt.Dimension(119, 31));
        jLabel2.setMinimumSize(new java.awt.Dimension(119, 31));
        jLabel2.setPreferredSize(new java.awt.Dimension(119, 31));

        cPinBtn.setBackground(new java.awt.Color(255, 166, 166));
        cPinBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        cPinBtn.setText("Change Pin");
        cPinBtn.addActionListener(this::cPinBtnActionPerformed);

        aboutUsBtn.setBackground(new java.awt.Color(255, 166, 166));
        aboutUsBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        aboutUsBtn.setText("About Us");
        aboutUsBtn.addActionListener(this::aboutUsBtnActionPerformed);

        backBtn.setBackground(new java.awt.Color(255, 166, 166));
        backBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout SettingPanelLayout = new javax.swing.GroupLayout(SettingPanel);
        SettingPanel.setLayout(SettingPanelLayout);
        SettingPanelLayout.setHorizontalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aboutUsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cPinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        SettingPanelLayout.setVerticalGroup(
            SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(65, 65, 65)
                .addComponent(cPinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(aboutUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cPinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPinBtnActionPerformed
        ChangePIn pin = new ChangePIn(accId);
        transition.switchFrame(this, pin);
        
    }//GEN-LAST:event_cPinBtnActionPerformed

    private void aboutUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsBtnActionPerformed
        AboutUs abous = new AboutUs();
        transition.switchFrame(this, abous);
    }//GEN-LAST:event_aboutUsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if(posit.equalsIgnoreCase("admin")){
            adminDashboard adminDash = new adminDashboard(accId);
            transition.switchFrame(this,adminDash);
        } else {
            udashboard dashboard = new udashboard(accId,frame,posit);
            transition.switchFrame(this,dashboard);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Setting().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JButton aboutUsBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cPinBtn;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}